### ISSUE TITLE
 Improv Wi-Fi Serial not detected wled

### ISSUE THREAD

**Issue by George-RG** [Aircoookie/WLED-WebInstaller#12]
Hello, I am new to all this so please excuse my cluelessness. 

I was trying to flash WLED on my new esp32 dev board. I bought it from waveshare and it has an ESP32-S3-WROOM-1 if that makes a difference. 

The problem is that when the installation finishes and I click next I get thrown back to the logs/installation menu instead of the configure WiFi menu. After some searching I found an error message in the console of the browser saying the following:

> Improv initialization failed. Error: Improv Wi-Fi Serial not detected
    at install-dialog-19322187.js:424:1210

If anyone has a clue about what could be the issue please write it below. 

Thanks in advance :)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
