### ISSUE TITLE
[WEB Installer] Lolin C3 mini loads but does't boot wled 

### ISSUE THREAD

**Issue by marcobrianza** [Aircoookie/WLED-WebInstaller#23]
Hello, just tested the web installer with release 0.14.2 on Lolin C3 mini
The installer does its thing but the board does not boot wled afterwards.
The serial writes these messages:

E (286) esp_core_dump_flash: No core dump partition found!
Ada
E (4856) phy_init: load_cal_data_from_nvs_handle: calibration data MAC check failed: expected 68:b6:b3:75:79:60, found a0:76:4e:43:be:70

FYI tasmota web installer works correctly on this board

**Comment by blazoncek** [comment]
New C3 bootloader has been added to web installer. Try it out and report.

**Comment by marcobrianza** [comment]
Hello, just tested and resulted a different error

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x4004d1f8
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
...

**Comment by blazoncek** [comment]
As I do not use web installer (and have no knowledge of its workings) I cannot help any further.
Please post any log files of the flashing process if you can find them.
Perhaps @Aircoookie will find the time to look into this issue but you are welcome to help and debug too.

P.S. Do not forget that S2, S3 and C3 are still in experimental phase and not all corners have been ironed out.

**Comment by lost-hope** [comment]
If i understand correctly, the bootloader offset for the C3 is 0x1000, partition 0x8000 and firmware 0x10000
https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32c3/security/secure-boot-bootloader-size.html
ATM it adds the bootloader on 0x0
i will change that and will ping you once you can try it on a seperate fork

**Comment by lost-hope** [comment]
@marcobrianza https://lost-hope.github.io/WLED-WebInstaller changed it for 0.14.2. please try

**Comment by marcobrianza** [comment]
Hello, the new repo has the same error, BUT 0.14.1 WORKS!

There is still this message at boot:
_E (286) esp_core_dump_flash: No core dump partition found!
Ada_
but is the same with the platform.io upload so I guess is not a matter of the web installer.

I have noted that the first time I use the web installer in a new board there is this message
_E (4980) phy_init: load_cal_data_from_nvs_handle: calibration data MAC check failed: expected a0:76:4e:1b:ed:2c, found a0:76:4e:43:be:7_0__

at following flashes of the same board this Disappears.

I am not sure how serious is this issue, but at least I checked that the default mac address of the baord is not overwritten because when the software load the mac address of WLED-AP is the correct one.

So I would use the method used for 0.14.1 because at least the board loads WLED that looks functional to me

**Comment by blazoncek** [comment]
> There is still this message at boot:
> _E (286) esp_core_dump_flash: No core dump partition found! Ada_
> but is the same with the platform.io upload so I guess is not a matter of the web installer.

If you want to play and get rid of the message, there are partition maps in the tools folder. Adjust and upload from PIO.

**Comment by lost-hope** [comment]
ok that was both really value able info, cause for 0.14.2 there was a bootloader change and an addition of the partion table. 
both removed/reverted now for 0.14.2 on my fork, so please try again

**Comment by marcobrianza** [comment]
yes this works, 
with the same boot message
_E (286) esp_core_dump_flash: No core dump partition found!
Ada_

**Comment by blazoncek** [comment]
Please close the issue if it is resolved.

**Comment by blazoncek** [comment]
For further discussion see: https://github.com/Aircoookie/WLED-WebInstaller/issues/22#issuecomment-2051136225
